site_name: ruff-fix-and-commit
site_url: 'https://ruff-fix-and-commit.readthedocs.io/'
site_author: Tsvika Shapira
site_description: ruff --fix & git commit.

repo_name: 'tsvikas/ruff-fix-and-commit'
repo_url: 'https://github.com/tsvikas/ruff-fix-and-commit'

theme:
  name: material
  # https://squidfunk.github.io/mkdocs-material/setup/

plugins:
  - search
  - gen-files:
      # https://oprypin.github.io/mkdocs-gen-files/index.html
      scripts:
        - scripts/gen_ref_pages.py
  - literate-nav:
      # https://oprypin.github.io/mkdocs-literate-nav/
      nav_file: SUMMARY.md
  - section-index  # https://oprypin.github.io/mkdocs-section-index/
  - mkdocstrings:
      # https://mkdocstrings.github.io/usage/
      default_handler: python
      handlers:
        python:
          # https://mkdocstrings.github.io/python/usage/
          paths: [src]

nav:
  - Home: index.md
  - Code Reference: reference/
